# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - centriqe-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://centriqecr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d960c0f1d10e4e56ac069b8bcc1fc729 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0ed5edc74a1841da9fea183f4fd95bb9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: centriqecr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d960c0f1d10e4e56ac069b8bcc1fc729 }}/centriqe-demo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'centriqe-demo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b892019d354648cba66a0d153db5281d }}
        images: 'centriqecr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d960c0f1d10e4e56ac069b8bcc1fc729 }}/centriqe-demo:${{ github.sha }}'